name: 1.0.$(BuildId)-$(SourceBranchName)

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: ./build.sh --AzureSubscriptionId='$(AzureSubscriptionId)' --AzureContainerRegistryName='$(AzureContainerRegistryName)' --AzureContainerRegistryUsername='$(AzureContainerRegistryUsername)' --AzureContainerRegistryPassword='$(AzureContainerRegistryPassword)'
  displayName: 'Lint, Build and Push'