# kubectl create --filename ./debug/busybox-pod.yaml --namespace=ummati-production
# kubectl exec --namespace ummati-production -it busybox -- nslookup home
# kubectl exec --namespace ummati-production -it busybox -- cat /etc/resolv.conf
# kubectl delete pod --namespace ummati-production busybox
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  restartPolicy: Always