apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    app.kubernetes.io/name: "{{ include "ummati.fullname" . }}-coredns-custom"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
data:
  azurestack.server: |
    azurestack.local:53 {
        forward . tls://1.1.1.1 tls://1.0.0.1 {
          tls_servername cloudflare-dns.com
          health_check 5s
        }
    }