apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "ummati.fullname" . }}-home-test"
  labels:
    app.kubernetes.io/name: "{{ include "ummati.fullname" . }}-home-test"
    app.kubernetes.io/component: "website"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
    "helm.sh/hook": test-success
spec:
  containers:
  - name: "{{ include "ummati.fullname" . }}-home-test"
    image: alpine:latest
    command: ["sh", "-c", "wget --output-document - --server-response {{ include "ummati.fullname" . }}-home"]
  restartPolicy: Never