apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: "{{ include "ummati.fullname" . }}-default-pod-preset"
  labels:
    app.kubernetes.io/name: "{{ include "ummati.fullname" . }}-default-pod-preset"
    app.kubernetes.io/component: "metadata"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      helm.sh/chart: {{ include "ummati.chart" . | quote }}
  env:
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KUBERNETES_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: KUBERNETES_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KUBERNETES_POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName