# Documentation: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: "high"
description: "A high priority class."
globalDefault: false
value: 1000000