# Documentation: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# TODO: change apiVersion to scheduling.k8s.io/v1 when upgraded to 1.14
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: "high"
  labels:
    app.kubernetes.io/name: "{{ include "ummati.fullname" . }}-high-priority-class"
    app.kubernetes.io/component: "metadata"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
description: "A high priority class."
globalDefault: false
value: 1000000