# Documentation: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: "low"
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
description: "A low priority class."
globalDefault: false
value: 0