apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "ummati.fullname" . }}-resource-quota
  labels:
    {{- include "ummati.defaultLabels" . | nindent 4 }}
spec:
  hard:
    cpu: {{ .Values.resourceQuota.cpu }}
    memory: {{ .Values.resourceQuota.memory | quote }}
    pods: {{ .Values.resourceQuota.pods }}