apiVersion: v1
kind: Service
metadata:
  name: {{ include "ummati.fullname" . }}
  labels:
    {{- include "ummati.defaultLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
