kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager-ummati-production
  namespace: ummati-production
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
