apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "ummati.fullname" . }}-home"
  labels:
    app.kubernetes.io/name: "{{ include "ummati.fullname" . }}-home"
    app.kubernetes.io/component: "website"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
  annotations:
    {{- include "ummati.defaultAnnotations" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment }}