# Documentation: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ummati.fullname" . }}-home
  labels:
    application: {{ include "ummati.fullname" . }}-home
    {{- include "ummati.defaultLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.home.replicas.minimum }}
  selector:
    matchLabels:
      application: {{ include "ummati.fullname" . }}-home
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.home.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.home.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        application: {{ include "ummati.fullname" . }}-home
    spec:
      containers:
        - name: {{ include "ummati.fullname" . }}-home
          {{- if hasKey .Values.home.image "registry" }}
          image: "{{ .Values.home.image.registry }}/{{ .Values.home.image.repository }}:{{ .Values.home.image.tag }}"
          {{- else }}
          image: "{{ .Values.home.image.repository }}:{{ .Values.home.image.tag }}"
          {{- end }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: {{ .Values.home.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.home.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.home.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.home.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: {{ .Values.home.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.home.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.home.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.home.readinessProbe.timeoutSeconds }}
          resources:
{{ toYaml .Values.home.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: {{ .Values.home.securityContext.readOnlyRootFilesystem }}
            runAsUser: {{ .Values.home.securityContext.runAsUser }}
      priorityClassName: {{ .Values.home.priorityClassName }}