# Documentation: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "ummati.fullname" . }}-home"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "ummati.fullname" . }}-home"
  maxReplicas: {{ .Values.home.replicas.maximum }}
  minReplicas: {{ .Values.home.replicas.minimum }}
  targetCPUUtilizationPercentage: {{ .Values.home.replicas.targetCPUUtilizationPercentage }}