# Documentation: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ummati.fullname" . }}-home
spec:
  {{- if hasKey .Values.home.podDisruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.home.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if hasKey .Values.home.podDisruptionBudget "minAvailable" }}
  minAvailable: {{ .Values.home.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      application: {{ include "ummati.fullname" . }}-home