# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ummati.fullname" . }}-home"
  labels:
    application: "{{ include "ummati.fullname" . }}-home"
    {{- include "ummati.defaultLabels" . | nindent 4 }}
spec:
  type: {{ .Values.home.service.type | quote }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    application: "{{ include "ummati.fullname" . }}-home"