# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ummati.fullname" . }}-home
  labels:
    application: {{ include "ummati.fullname" . }}-home
    {{- include "ummati.defaultLabels" . | nindent 4 }}
spec:
  type: {{ .Values.home.service.type }}
  ports:
    - port: {{ .Values.home.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application: {{ include "ummati.fullname" . }}-home